version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - osdcloud-cache:/home/vscode/OSDCloud:cached
    command: sleep infinity
    environment:
      - POWERSHELL_TELEMETRY_OPTOUT=1
      - POWERSHELL_UPDATECHECK=Off
    # Add resource limits to prevent container from consuming too much memory
    mem_limit: 4g
    mem_reservation: 1g

volumes:
  osdcloud-cache:
